// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const updateUserPasswordEmail = `-- name: UpdateUserPasswordEmail :one
UPDATE users SET updated_at = NOW(), email = $2, hashed_password = $3 WHERE id = $1
RETURNING id, created_at, updated_at, email, is_chirpy_red
`

type UpdateUserPasswordEmailParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

type UpdateUserPasswordEmailRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	IsChirpyRed bool
}

func (q *Queries) UpdateUserPasswordEmail(ctx context.Context, arg UpdateUserPasswordEmailParams) (UpdateUserPasswordEmailRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserPasswordEmail, arg.ID, arg.Email, arg.HashedPassword)
	var i UpdateUserPasswordEmailRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.IsChirpyRed,
	)
	return i, err
}

const upgradeUserToChirpyRedByID = `-- name: UpgradeUserToChirpyRedByID :exec
UPDATE users SET is_chirpy_red = $2 WHERE id = $1
`

type UpgradeUserToChirpyRedByIDParams struct {
	ID          uuid.UUID
	IsChirpyRed bool
}

func (q *Queries) UpgradeUserToChirpyRedByID(ctx context.Context, arg UpgradeUserToChirpyRedByIDParams) error {
	_, err := q.db.ExecContext(ctx, upgradeUserToChirpyRedByID, arg.ID, arg.IsChirpyRed)
	return err
}
